services:
  - type: web
    name: lumora-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: API_KEY
        value: "AIzaSyCs1z3K_oD6GHD9NtlWiKAWTbFke4tfTio"
